name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
            distribution: 'corretto'
            java-version: '21'

      - name: application.yml 생성
        run: |
          # create application.yml
          cd src/main/resources
          
          # application.yml 파일 생성
          touch ./application.yml
          
          # GitHub-Actions 에서 설정한 값을 application-secret.yml 파일에 쓰기..git
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: 빌드
        run: |
          chmod +x gradlew
          ./gradlew build -x test
        shell: bash